<!-- Finance Summary Print Template -->
<?php
$totalIncome = $totalIncome ?? 0;
$totalExpenses = $totalExpenses ?? 0;
$incomeByCategory = $incomeByCategory ?? [];
$expenseByCategory = $expenseByCategory ?? [];
$user = Auth::user() ?? [];
$startDate = $startDate ?? date('Y-m-01');
$endDate = $endDate ?? date('Y-m-t');
?>
<div class="info-grid">
    <div class="info-box">
        <label>Report Type</label>
        <span>Financial Summary</span>
    </div>
    <div class="info-box">
        <label>Period</label>
        <span><?= formatDate($startDate) ?> to <?= formatDate($endDate) ?></span>
    </div>
    <div class="info-box">
        <label>Generated By</label>
        <span><?= e(((Auth::user()['first_name'] ?? '') . ' ' . (Auth::user()['last_name'] ?? '')) ?: 'System') ?></span>
    </div>
    <div class="info-box">
        <label>Date Generated</label>
        <span><?= date(DISPLAY_DATETIME_FORMAT) ?></span>
    </div>
</div>

<h3>Income vs Expenses</h3>
<div style="margin-bottom: 30px;">
    <table style="width: 100%; border: none;">
        <tr>
            <td style="border: none; padding: 0; vertical-align: top; width: 48%;">
                <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; border: 1px solid #dcfce7;">
                    <h4 style="color: #166534; margin-top: 0;">Total Income</h4>
                    <p style="font-size: 24pt; font-weight: bold; color: #166534; margin: 0;"><?= formatCurrency($totalIncome, $currency ?? 'USD') ?></p>
                </div>
            </td>
            <td style="border: none; padding: 0; width: 4%;"></td>
            <td style="border: none; padding: 0; vertical-align: top; width: 48%;">
                <div style="background: #fef2f2; padding: 20px; border-radius: 8px; border: 1px solid #fee2e2;">
                    <h4 style="color: #991b1b; margin-top: 0;">Total Expenses</h4>
                    <p style="font-size: 24pt; font-weight: bold; color: #991b1b; margin: 0;"><?= formatCurrency($totalExpenses, $currency ?? 'USD') ?></p>
                </div>
            </td>
        </tr>
    </table>
    
    <div style="margin-top: 20px; background: #f8fafc; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; text-align: center;">
        <h4 style="color: #0f172a; margin-top: 0;">Net Profit</h4>
        <p style="font-size: 28pt; font-weight: bold; color: <?= ($totalIncome - $totalExpenses) >= 0 ? '#166534' : '#991b1b' ?>; margin: 0;">
            <?= formatCurrency($totalIncome - $totalExpenses, $currency ?? 'USD') ?>
        </p>
    </div>
</div>

<h3>Income Breakdown</h3>
<table>
    <thead>
        <tr>
            <th>Category</th>
            <th style="text-align: right;">Amount</th>
            <th style="text-align: right;">% of Total</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($incomeByCategory)): ?>
        <?php foreach ($incomeByCategory as $category): ?>
        <tr>
            <td><?= e($category['category']) ?></td>
            <td style="text-align: right;"><?= formatCurrency($category['total'], $currency ?? 'USD') ?></td>
            <td style="text-align: right;"><?= $totalIncome > 0 ? round(($category['total'] / $totalIncome) * 100, 1) : 0 ?>%</td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="3" style="text-align: center; color: #999;">No income recorded</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>

<h3>Expense Breakdown</h3>
<table>
    <thead>
        <tr>
            <th>Category</th>
            <th style="text-align: right;">Amount</th>
            <th style="text-align: right;">% of Total</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($expenseByCategory)): ?>
        <?php foreach ($expenseByCategory as $category): ?>
        <tr>
            <td><?= e($category['category']) ?></td>
            <td style="text-align: right;"><?= formatCurrency($category['total'], $currency ?? 'USD') ?></td>
            <td style="text-align: right;"><?= $totalExpenses > 0 ? round(($category['total'] / $totalExpenses) * 100, 1) : 0 ?>%</td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="3" style="text-align: center; color: #999;">No expenses recorded</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
